#!/usr/bin/env node
// Downloads the cburnett piece set (Colin M.L. Burnett) from lichess's mirror and writes it as a
// TypeScript module so the server needs no asset path at runtime. Run once; commit the output.
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SOURCE = 'https://raw.githubusercontent.com/lichess-org/lila/master/public/piece/cburnett';
const PIECES = ['wK', 'wQ', 'wR', 'wB', 'wN', 'wP', 'bK', 'bQ', 'bR', 'bB', 'bN', 'bP'];
const target = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../apps/server/src/images/pieces.ts',
);

function inner(svg) {
  const open = svg.match(/<svg\b[^>]*>/);
  if (!open || !/viewBox="0 0 45 45"/.test(open[0])) throw new Error('unexpected piece svg');
  return svg
    .slice(open.index + open[0].length)
    .replace(/<\/svg>\s*$/, '')
    .trim();
}

const entries = [];
for (const piece of PIECES) {
  const response = await fetch(`${SOURCE}/${piece}.svg`);
  if (!response.ok) throw new Error(`${piece}: HTTP ${response.status}`);
  entries.push(`  ${piece}: ${JSON.stringify(inner(await response.text()))},`);
}
const header = `// Generated by scripts/vendor-pieces.mjs — do not edit by hand.
// cburnett chess pieces by Colin M.L. Burnett, used under CC BY-SA 3.0 (see ATTRIBUTION.md).
// Each entry is the content of a 45 × 45 SVG without its outer <svg> element.
`;
await mkdir(dirname(target), { recursive: true });
await writeFile(
  target,
  `${header}\nexport const PIECE_VIEWBOX = 45;\n\nexport const PIECES = {\n${entries.join('\n')}\n} as const;\n\nexport type PieceCode = keyof typeof PIECES;\n`,
);
console.log(`wrote ${target}`);
